### ISSUE TITLE
구현 명세 목록

### ISSUE THREAD

**Issue by x86chi** [x86chi/TodoList#3]
## 기능 요구사항
- [x] 할일 목록을 볼 수 있다. 
- - - -
- [x] 새로운 TODO*를 작성할 수 있다. 
- [x] 항목의 제목과 내용을 수정할 수 있다.
- [x] 항목을 삭제할 수 있다. 
- [x] 사용자의 선택에 의해 마감기한을 넣을 수 있다. 
- [x] 항목의 우선순위를 조절할 수 있다. 
- [x] TODO항목에 대한 완료 처리를 할 수 있다. 
- [x] 마감기한이 지난 TODO에 대해 알림을 노출할 수 있다.
> *제목과 내용

## 구현 명세
- [x] TODO 목록을 불러온다
- [x] 컴포넌트를 구현한다
- [x] 새 항목을 작성하는 모달 구현
- [x] 기존 항목 삭제 시 TODO 재맵핑
- [x] 기존 항목을 수정하는 액션
## 성능 요구사항
- [ ] TODO 이용 시 발생하는 오류사항을 ~~최소화한다.~~ : 알람 스케줄링 버그(#6) 
- [x] 오류 발생 시 사용자가 이해하기 쉽게 표시한다. 
- [x] 다른 사람이 읽기 쉬운 코드를 작성한다. 
- [x] HTML/CSS에서 사용할 수 있는 최신 구조와 기술을 사용한다. 

## 인터페이스 요구사항 
- [x] 직관적이고 의미 전달이 명확한 화면을 사용자에게 제공한다. 

## 제출물 
- [x] 소스코드가 담긴 저장소 URL 
	- README에는 해당 웹서버를 리눅스 기준으로 실행하기 위해 필요한 설치 및 빌드 방법이 작성되어 있어야 합니다. 

- [x] 접속하여 테스트 가능한 URL
	- heroku, AWS등 서버에 배포하여 기능을 직접 사용해볼 수 있어야 합니다.

**Comment by BetaF1sh** [comment]
## 푸쉬 알림 구현 완료

<img width="350" alt="Screen Shot 2019-05-19 at 11 35 44 PM" src="https://user-images.githubusercontent.com/5278201/57984317-99c43800-7a95-11e9-8b35-fe9f7efdd58a.png">

알람 스케줄링을 30초 간격으로 `setInterval()`를 돌려 해결했습니다(...)

## 남은 일
| 모달 UI | 항목 UI |
| :--: | :--:|
|<img width="300" alt="Screen Shot 2019-05-20 at 12 26 49 AM" src="https://user-images.githubusercontent.com/5278201/57984551-d729c500-7a97-11e9-8cc7-ead7037fecfa.png">|<img width="186" alt="Screen Shot 2019-05-20 at 12 41 10 AM" src="https://user-images.githubusercontent.com/5278201/57984600-4a333b80-7a98-11e9-8571-f8c140f35f63.png">|

- [ ] 모달 UI 개선하기
- [ ] 항목에 적힌 기한을 `4분 남음`, `4시간 남음` 같이 가독성 있게 포멧 하기

**Comment by BetaF1sh** [comment]
알람 스케줄링 버그로 인해 이슈 재오픈

**Comment by x86chi** [comment]
#6 이슈로 위임함
